### ISSUE TITLE
autoclean feature and BACKUP list?

### ISSUE THREAD

**Issue by YAmikep** [hellp/saferedisqueue#6]
Hi Fabian,

Sorry to create a new ticket but this time it's more a question regarding the autoclean feature and the BACKUP list. I'm not sure to understand how it works.

I do not want the items to be requeued automatically if they are unacknowledged so I will disabled autoclean.
However, how can I see the items that are unacknowledged if I want to requeue them manually?
Is there an easy way to see that? Will they be in the ACKBUF list? 

It looks like I cannot make the difference between the ones that are unackowledged for a long time or the ones that have just been moved and are being processed, correct?

Thanks
Michael

**Comment by hellp** [comment]
If autoclean is disabled, the _ids_ of `pop`ed items are in ACKBUF, correct. With autoclean enabled they move from ACKBUF to BACKUP at one point, so they may be in one of them. So when autoclean is disabled you have no indication how long they've been in there.

We have some shell script in an internal project to introspect the queues. Haven't looked at this in a long time, because I'm not too involved in this subsystem anymore. We also have some monitoring (Nagios) for the lengths of many of our queues.

**Comment by YAmikep** [comment]
Ok I see, So when autoclean is disabled, they should stay in the BACKUP list forever then.

Thanks for the input.

**Comment by hellp** [comment]
No, without autoclean, they stay in ACKBUF forever. BACKUP not used at all in this case.
